name: faith_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0
  google_mobile_ads: ^5.2.0
  html: ^0.15.5
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
